logging:
  level:
    root: info

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_library
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    #hibernate:
      #ddl-auto: create
application:
  some:
    parameter: "some real value"
    other:
      parameter: "another real value"